import type { Metadata } from "next";
import {Source_Code_Pro} from "next/font/google"
import "./globals.css";

const sourceCodePro = Source_Code_Pro({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  style: ['italic', 'normal'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
